const mongoose = require("mongoose");
const ownerId=new mongoose.Types.ObjectId("69a3c72fcb291eda439444a2");


const sampleListings = [
{
  title: "Cozy Beachfront Cottage",
  description: "Escape to this charming beachfront cottage with stunning ocean views.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b" },
  price: 1500,
  location: "Malibu",
  country: "United States",
  category: "Beachfront",
  owner: ownerId,
  reviews: [],
},
{
  title: "Modern Loft in Downtown",
  description: "Stylish loft apartment perfect for urban explorers.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470" },
  price: 1200,
  location: "New York City",
  country: "United States",
  category: "Trending",
  owner: ownerId,
  reviews: [],
},
{
  title: "Mountain Retreat Cabin",
  description: "Peaceful mountain cabin surrounded by nature.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d" },
  price: 1000,
  location: "Aspen",
  country: "United States",
  category: "Mountainside",
  owner: ownerId,
  reviews: [],
},
{
  title: "Historic Villa in Tuscany",
  description: "Experience Tuscany in this beautifully restored villa.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945" },
  price: 2500,
  location: "Florence",
  country: "Italy",
  category: "Historical",
  owner: ownerId,
  reviews: [],
},
{
  title: "Secluded Treehouse Getaway",
  description: "Live among the treetops in this unique retreat.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4" },
  price: 800,
  location: "Portland",
  country: "United States",
  category: "Treehouses",
  owner: ownerId,
  reviews: [],
},
{
  title: "Beachfront Paradise Condo",
  description: "Step out directly onto the sandy beach.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9" },
  price: 2000,
  location: "Cancun",
  country: "Mexico",
  category: "Beachfront",
  owner: ownerId,
  reviews: [],
},
{
  title: "Rustic Cabin by the Lake",
  description: "Perfect lake getaway for outdoor lovers.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b" },
  price: 900,
  location: "Lake Tahoe",
  country: "United States",
  category: "Tinyhomes",
  owner: ownerId,
  reviews: [],
},
{
  title: "Luxury Penthouse Views",
  description: "Panoramic city views from a stunning penthouse.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd" },
  price: 3500,
  location: "Los Angeles",
  country: "United States",
  category: "Trending",
  owner: ownerId,
  reviews: [],
},
{
  title: "Ski Chalet in Swiss Alps",
  description: "Ski-in/ski-out chalet in the Alps.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb" },
  price: 3000,
  location: "Verbier",
  country: "Switzerland",
  category: "Mountainside",
  owner: ownerId,
  reviews: [],
},
{
  title: "Safari Lodge Adventure",
  description: "Luxury safari lodge experience.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e" },
  price: 4000,
  location: "Serengeti",
  country: "Tanzania",
  category: "Camping",
  owner: ownerId,
  reviews: [],
},
{
  title: "Private Island Retreat",
  description: "Entire island just for you.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972" },
  price: 10000,
  location: "Fiji",
  country: "Fiji",
  category: "Trending",
  owner: ownerId,
  reviews: [],
},
{
  title: "Charming Farm Cottage",
  description: "Countryside farm stay with peace and greenery.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f" },
  price: 1200,
  location: "Cotswolds",
  country: "United Kingdom",
  category: "Farms",
  owner: ownerId,
  reviews: [],
},
{
  title: "Historic Brownstone Boston",
  description: "Elegant historic home in Boston.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1533619239233-6280475a633a" },
  price: 2200,
  location: "Boston",
  country: "United States",
  category: "Historical",
  owner: ownerId,
  reviews: [],
},
{
  title: "Beachfront Bungalow Bali",
  description: "Private pool bungalow in Bali.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602391833977-358a52198938" },
  price: 1800,
  location: "Bali",
  country: "Indonesia",
  category: "Beachfront",
  owner: ownerId,
  reviews: [],
},
{
  title: "Mountain View Cabin Banff",
  description: "Breathtaking mountain views in Banff.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb" },
  price: 1500,
  location: "Banff",
  country: "Canada",
  category: "Mountainside",
  owner: ownerId,
  reviews: [],
},
{
  title: "Art Deco Apartment Miami",
  description: "Stylish 1920s inspired apartment.",
  image: { filename: "listingimage", url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579" },
  price: 1600,
  location: "Miami",
  country: "United States",
  category: "Trending",
  owner: ownerId,
  reviews: [],
},
{
  title: "Tropical Villa Phuket",
  description: "Luxury tropical villa with infinity pool.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9" },
  price: 3000,
  location: "Phuket",
  country: "Thailand",
  category: "Hotel",
  owner: ownerId,
  reviews: [],
},
{
  title: "Historic Castle Scotland",
  description: "Live like royalty in Scotland.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98" },
  price: 4000,
  location: "Scottish Highlands",
  country: "United Kingdom",
  category: "Historical",
  owner: ownerId,
  reviews: [],
},
{
  title: "Desert Oasis Dubai",
  description: "Luxury desert oasis experience.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518684079-3c830dcef090" },
  price: 5000,
  location: "Dubai",
  country: "United Arab Emirates",
  category: "Hotel",
  owner: ownerId,
  reviews: [],
},
{
  title: "Eco-Friendly Dome Retreat",
  description: "Stay in a beautiful eco dome.",
  image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7" },
  price: 900,
  location: "Costa Rica",
  country: "Costa Rica",
  category: "Domes",
  owner: ownerId,
  reviews: [],
}
];

module.exports = { data: sampleListings };
